# Generated by Django 2.2 on 2020-12-04 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('store_location1', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/store/')),
                ('eggless_price', models.FloatField(default=0.0)),
                ('sugar_less_price', models.FloatField(default=0.0)),
                ('flat_eggless', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ManyToManyField(blank=True, related_name='store_slocation', to='store.Location')),
            ],
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_star', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer_purchased', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_customer_store', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_review', to='store.Store')),
            ],
        ),
    ]
