# Generated by Django 2.2 on 2020-12-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/store/banner/'),
        ),
    ]
