# Generated by Django 2.2 on 2021-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contact_number',
            field=models.CharField(default='9803622821', max_length=12),
            preserve_default=False,
        ),
    ]
