# Generated by Django 2.2 on 2023-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_location_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Factories',
                'ordering': ('-id',),
            },
        ),
    ]
