# Generated by Django 2.2 on 2020-12-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingFullBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing')),
                ('redirect_url', models.CharField(max_length=800)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SectionOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing')),
                ('redirect_url_1', models.CharField(max_length=800)),
                ('image_2', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing')),
                ('redirect_url_2', models.CharField(max_length=800)),
                ('image_3', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing')),
                ('redirect_url_3', models.CharField(max_length=800)),
                ('image_4', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing')),
                ('redirect_url_4', models.CharField(max_length=800)),
                ('image_5', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing')),
                ('redirect_url_5', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'SectionOne',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PopularFlavourSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Flavour')),
            ],
        ),
        migrations.CreateModel(
            name='LandingCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ExploreStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='BestSellersSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
