# Generated by Django 2.2 on 2020-12-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_banner_image'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestsellerssection',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='best_seller_section', to='store.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explorestore',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='explore_stores', to='store.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingcategories',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='landing_categories', to='store.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingfullbanner',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='full_banner', to='store.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularflavoursection',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='popular_flavour', to='store.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionone',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='section_one', to='store.Location'),
            preserve_default=False,
        ),
    ]
