# Generated by Django 2.2 on 2020-12-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20201214_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcategories',
            name='image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='images/landing/categories/'),
        ),
    ]
