# Generated by Django 2.2 on 2020-12-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
        migrations.DeleteModel(
            name='EsewaCredential',
        ),
        migrations.DeleteModel(
            name='KhaltiCredential',
        ),
    ]
