# Generated by Django 2.2 on 2020-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(choices=[('Flat', 'Flat Price'), ('Percentage', 'Percentage')], max_length=250)),
                ('value', models.FloatField()),
                ('coupon_number', models.CharField(max_length=50, unique=True)),
                ('total_user_limit', models.IntegerField()),
                ('per_user_limit', models.IntegerField()),
                ('time_limit', models.DateField()),
                ('min_cart_price', models.FloatField()),
                ('max_cart_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
