# Generated by Django 2.2.5 on 2021-03-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210304_0938'),
        ('store', '0003_store_contact_number'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcoupon',
            name='category',
            field=models.ManyToManyField(related_name='coupon_category', to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='cartcoupon',
            name='product',
            field=models.ManyToManyField(related_name='coupon_product', to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='cartcoupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_store', to='store.Store'),
        ),
    ]
