# Generated by Django 2.2.5 on 2021-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20210307_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcoupon',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='coupon_category', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='coupon_product', to='catalog.Product'),
        ),
    ]
