# Generated by Django 2.2 on 2021-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
    ]
