# Generated by Django 2.2.5 on 2021-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210317_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dispatcher',
            field=models.BooleanField(default=False),
        ),
    ]
