# Generated by Django 2.2 on 2022-02-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.Store'),
        ),
    ]
