# Generated by Django 2.2 on 2022-07-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220204_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
