# Generated by Django 2.2 on 2022-08-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_production_manager',
            field=models.BooleanField(default=False),
        ),
    ]
