# Generated by Django 2.2 on 2023-02-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_factories'),
        ('accounts', '0009_userprofile_is_production_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='store.Factories'),
        ),
    ]
