# Generated by Django 2.2 on 2023-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_factory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooTokenStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
