# Generated by Django 2.2 on 2023-04-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_odootokenstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='odootokenstore',
            name='partner_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
