# Generated by Django 2.2 on 2023-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_odootokenstore_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='odootokenstore',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
