# Generated by Django 2.2 on 2023-04-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_odootokenstore_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odootokenstore',
            old_name='session_id',
            new_name='session_key',
        ),
    ]
