# Generated by Django 2.2 on 2020-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionlDeliveryCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_min_amount', models.IntegerField()),
                ('cart_max_amount', models.IntegerField()),
                ('delivery_charge', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Conditionl Delivery Charge',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('delivery_charge', models.FloatField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OutletBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTaxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('is_compound', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(max_length=100)),
                ('outlet_type', models.CharField(blank=True, max_length=250, null=True)),
                ('store_address', models.CharField(max_length=250)),
                ('delivery_charge', models.FloatField(blank=True, default=0, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=13, null=True)),
                ('contact_number', models.CharField(max_length=13)),
                ('currency', models.CharField(choices=[('Rs', 'Nepalese Rupee (Rs)'), ('INR', 'Indian Rupee (INR)'), ('$', 'US Dollor (USD)'), ('€', 'Euro (€)'), ('£', 'Pound (£)'), ('AUD', 'Australian Dollor (AU.$)'), ('CAD', 'Canadian Dollor (CA.$)')], default='Rs', max_length=100)),
                ('delivery_available_time', models.CharField(max_length=150)),
                ('minimum_order_price', models.FloatField(blank=True, null=True)),
                ('brand_color', models.CharField(blank=True, max_length=150, null=True)),
                ('banner_image', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/settings')),
                ('banner_image_2', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/settings')),
                ('banner_image_3', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/settings')),
                ('outlet_logo', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/settings')),
                ('aggregator_image', models.ImageField(blank=True, max_length=700, null=True, upload_to='images/settings')),
                ('apply_extra_charge', models.BooleanField(default=False)),
                ('flat_delivery', models.BooleanField(default=False)),
                ('is_conditional_delivery_charge', models.BooleanField(default=False)),
                ('is_locations_delivery_charge', models.BooleanField(default=False)),
                ('nepxpress_username', models.CharField(blank=True, max_length=500, null=True)),
                ('nepxpress_password', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_top_message', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_top_message_redirect', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShippingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Time',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_time', models.ManyToManyField(related_name='shipping_time', to='settings.ShippingTime')),
            ],
            options={
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ('-id',),
            },
        ),
    ]
