# Generated by Django 2.2 on 2020-12-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
