# Generated by Django 2.2.5 on 2021-03-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201208_0641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionlDeliveryCharge',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SalesTaxes',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
    ]
