# Generated by Django 2.2.5 on 2021-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210304_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='script_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
