# Generated by Django 2.2 on 2020-12-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='cost_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
