# Generated by Django 2.2 on 2020-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvarient_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_props',
            field=models.BooleanField(default=False),
        ),
    ]
