# Generated by Django 2.2 on 2020-12-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='occasion',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaddons',
            name='types',
            field=models.CharField(choices=[('Candle', 'Candle'), ('Ballons', 'Ballons'), ('Spray', 'Spray'), ('Chocolates', 'Chocolates'), ('Gifts', 'Gifts'), ('Birthday Cards', 'Birthday Cards'), ('Bouquet /Flowers', 'Bouquet /Flowers'), ('Birthday Hats', 'Birthday Hats'), ('Party Popper', 'Party Popper'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
