# Generated by Django 2.2 on 2020-12-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201227_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
