# Generated by Django 2.2 on 2021-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201227_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
        migrations.AddField(
            model_name='category',
            name='is_type',
            field=models.BooleanField(default=True),
        ),
    ]
