# Generated by Django 2.2 on 2021-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210106_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.SlugField(),
        ),
    ]
