# Generated by Django 2.2 on 2021-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210125_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
