# Generated by Django 2.2.5 on 2021-02-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210218_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='is_quick_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='product_tags', to='catalog.Tags'),
        ),
    ]
