# Generated by Django 2.2.5 on 2021-03-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210219_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occasion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
