# Generated by Django 2.2 on 2021-03-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210304_0938'),
        ('catalog', '0009_auto_20210321_0631'),
    ]

    operations = [
    ]
