# Generated by Django 2.2 on 2021-03-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210321_0711'),
        ('catalog', '0012_merge_20210321_0648'),
    ]

    operations = [
    ]
