# Generated by Django 2.2.5 on 2021-06-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210324_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaddons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
