# Generated by Django 2.2 on 2020-12-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20201214_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='sender_address',
            field=models.CharField(default='c-c', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA'), ('IME', 'IME'), ('CARD', 'CARD'), ('COD', 'COD')], default='COD', max_length=20),
        ),
    ]
