# Generated by Django 2.2 on 2021-01-06 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20201227_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Unconfirmed', 'Placed'), ('Confirmed', 'Accepted'), ('Dispatched', 'Processed'), ('Complete', 'Completed'), ('Cancelled', 'Cancelled')], default='Unconfirmed', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Awaiting Payment', 'Awaiting Payment'), ('Paid', 'Paid'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Paid', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addonitem',
            name='addons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_addons', to='catalog.ProductAddons'),
        ),
        migrations.AlterField(
            model_name='addonorderitem',
            name='addons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderitem_addons', to='catalog.ProductAddons'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='sales.DeliveryAddress'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_varient', to='catalog.ProductVarient'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitem_shipping_method', to='settings.ShippingMethod'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_shipping_time', to='settings.ShippingTime'),
        ),
    ]
