# Generated by Django 2.2 on 2021-01-25 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_contact_number'),
        ('settings', '0002_auto_20201208_0641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_auto_20210106_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_from',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Picked', 'Picked'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(default='123456qwert', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_shipping_time', to='settings.ShippingTime'),
        ),
        migrations.AlterField(
            model_name='addonorderitem',
            name='addons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_addons', to='catalog.ProductAddons'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='receiver_address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Unconfirmed', 'Placed'), ('Processing', 'Processed'), ('Confirmed', 'Confirmed'), ('Complete', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Awaiting Payment', 'Awaiting Payment'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='sales.Order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_delivery_store', to='store.Store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
