# Generated by Django 2.2 on 2021-02-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210125_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Awaiting Payment', 'Awaiting Payment'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], max_length=20),
        ),
    ]
