# Generated by Django 2.2.5 on 2021-03-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20210203_0717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderExtraCharge',
        ),
    ]
