# Generated by Django 2.2.5 on 2021-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_delete_orderextracharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='receiver_landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
