# Generated by Django 2.2.5 on 2021-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20210304_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='receiver_area',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='receiver_city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
