# Generated by Django 2.2.5 on 2021-03-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210311_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='occasion',
            field=models.CharField(blank=True, choices=[('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('BABY SHOWER', 'Baby Shower'), ('WEEDING', 'Weeding')], max_length=15, null=True),
        ),
    ]
