# Generated by Django 2.2.5 on 2021-03-23 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20210323_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='receiver_contact_number2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,20}$')]),
        ),
    ]
