# Generated by Django 2.2.5 on 2021-06-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20210614_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
    ]
