# Generated by Django 2.2.5 on 2021-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_vendor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA'), ('IME', 'IME'), ('CARD', 'CARD'), ('COD', 'COD'), ('COD FONEPAY', 'COD FONEPAY')], default='COD', max_length=20),
        ),
    ]
