# Generated by Django 2.2.5 on 2021-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20210620_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA'), ('IME', 'IME'), ('CARD', 'CARD'), ('COD', 'COD'), ('COD FONEPAY', 'COD FONEPAY')], default='COD', max_length=20),
        ),
    ]
