# Generated by Django 2.2.5 on 2021-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20210620_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
