# Generated by Django 2.2.5 on 2021-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA'), ('IME', 'IME'), ('CARD', 'CARD'), ('COD', 'COD'), ('COD FONEPAY', 'COD FONEPAY'), ('COD ESEWA', 'COD ESEWA'), ('COD KHALTI', 'COD KHALTI')], default='COD', max_length=20),
        ),
    ]
