# Generated by Django 2.2.5 on 2021-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20210622_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Unconfirmed', 'Placed'), ('Processing', 'Processed'), ('Confirmed', 'Confirmed'), ('Complete', 'Completed'), ('Cancelled', 'Cancelled'), ('Ready To Dispatched', 'Ready To Dispatched')], max_length=20),
        ),
    ]
