# Generated by Django 2.2.5 on 2021-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20210622_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Unconfirmed', 'Placed'), ('Processing', 'Processed'), ('Confirmed', 'Confirmed'), ('Complete', 'Completed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched')], max_length=20),
        ),
    ]
