# Generated by Django 2.2.5 on 2021-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20210622_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
