# Generated by Django 2.2.5 on 2021-06-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_orderdelivery_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='expected_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
