# Generated by Django 2.2.5 on 2021-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_deliveryaddress_social_media_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='photo_cake_image1',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='cart/photocake/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='photo_cake_image2',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='cart/photocake/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='photo_cake_image3',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='cart/photocake/'),
        ),
    ]
