# Generated by Django 2.2.5 on 2021-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20210630_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonorderitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
