# Generated by Django 2.2.5 on 2021-07-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_addonorderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA'), ('IME', 'IME'), ('CARD', 'CARD'), ('COD', 'COD'), ('CREDIT', 'CREDIT'), ('BANK', 'BANK'), ('FONEPAY', 'FONEPAY'), ('COD FONEPAY', 'COD FONEPAY'), ('COD ESEWA', 'COD ESEWA'), ('COD KHALTI', 'COD KHALTI')], default='COD', max_length=20),
        ),
    ]
