# Generated by Django 2.2 on 2021-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_auto_20210709_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='flavour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
