# Generated by Django 2.2 on 2021-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_auto_20210715_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='source',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Phone', 'Phone'), ('WhatsApp', 'WhatsApp'), ('Bakery Order', 'Bakery Order'), ('Oho Staffs', 'Oho Staffs'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
