# Generated by Django 2.2 on 2021-07-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_auto_20210729_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='type_of_cake',
            field=models.CharField(choices=[('Basic Fondent', 'Basic Fondent'), ('Fondent Cake', 'Fondent Cake'), ('Mini Cake', 'Mini Cake'), ('Normal Cake', 'Normal Cake')], max_length=15, null=True),
        ),
    ]
