# Generated by Django 2.2 on 2021-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_deliveryaddress_type_of_cake'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('threshold', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Order Alert',
                'verbose_name_plural': 'Order Alerts',
            },
        ),
    ]
