# Generated by Django 2.2 on 2022-01-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_orderalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_refrence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
