# Generated by Django 2.2 on 2022-01-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_order_cancelled_refrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
