# Generated by Django 2.2 on 2022-01-27 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_script_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_productaddons_is_active'),
        ('sales', '0040_orderassignedtovendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrderItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flavour', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(help_text='Unit price of the product')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sub_total', models.FloatField()),
                ('total', models.FloatField()),
                ('special_instruction', models.TextField(blank=True, max_length=400, null=True)),
                ('is_sugerless', models.BooleanField()),
                ('is_eggless', models.BooleanField()),
                ('pound', models.FloatField()),
                ('photo_cake_image', models.TextField(blank=True, max_length=700, null=True)),
                ('photo_cake_image1', models.TextField(blank=True, max_length=700, null=True)),
                ('photo_cake_image2', models.TextField(blank=True, max_length=700, null=True)),
                ('photo_cake_image3', models.TextField(blank=True, max_length=700, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.Order')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.ProductVarient')),
                ('shipping_method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='settings.ShippingMethod')),
            ],
            options={
                'verbose_name': 'historical order item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=100)),
                ('total', models.FloatField()),
                ('sub_total_order', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('coupon', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('order_status', models.CharField(choices=[('Unconfirmed', 'Placed'), ('Processing', 'Processed'), ('Confirmed', 'Confirmed'), ('Complete', 'Completed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Awaiting Payment', 'Awaiting Payment'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], max_length=20)),
                ('delivery_status', models.CharField(blank=True, choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Picked', 'Picked'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('placed_on', models.DateField(blank=True, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('accepted_on', models.DateTimeField(blank=True, null=True)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('dispatched_on', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA'), ('IME', 'IME'), ('CARD', 'CARD'), ('COD', 'COD'), ('CREDIT', 'CREDIT'), ('BANK', 'BANK'), ('FONEPAY', 'FONEPAY'), ('COD FONEPAY', 'COD FONEPAY'), ('COD ESEWA', 'COD ESEWA'), ('COD KHALTI', 'COD KHALTI')], default='COD', max_length=20)),
                ('date', models.DateField(null=True)),
                ('delivery_sent_nepxpress', models.BooleanField(default=False)),
                ('delivery_assigned', models.CharField(blank=True, max_length=250, null=True)),
                ('reference', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cancelled_refrence', models.CharField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.DeliveryAddress')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='settings.ShippingTime')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.Vendor')),
            ],
            options={
                'verbose_name': 'historical order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
