# Generated by Django 2.2 on 2022-01-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_historicalorder_historicalorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='shipping_method',
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderItem',
        ),
    ]
