# Generated by Django 2.2 on 2022-01-28 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_orderitemlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
