# Generated by Django 2.2 on 2022-01-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_orderitemlogs_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemLogs',
        ),
    ]
