# Generated by Django 2.2 on 2022-01-28 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0045_delete_orderitemlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', jsonfield.fields.JSONField(default=dict)),
                ('order_item', jsonfield.fields.JSONField(default=dict)),
                ('addons', jsonfield.fields.JSONField(default=dict)),
                ('log_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_order_item_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
