# Generated by Django 2.2 on 2022-01-28 07:09

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_orderlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlogs',
            name='order_data_log',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orderlogs',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_log', to='sales.Order'),
        ),
    ]
