# Generated by Django 2.2 on 2022-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_auto_20220128_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odoo_status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Success', 'Success'), ('Failed', 'Failed')], default='None', max_length=20, null=True),
        ),
    ]
