# Generated by Django 2.2 on 2022-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_auto_20220824_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched_ready_on',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
