# Generated by Django 2.2 on 2022-09-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_order_dispatched_ready_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched_ready_on_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
