# Generated by Django 2.2 on 2023-02-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_order_dispatched_ready_on_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factory_delivery_order', to='store.Factories'),
        ),
    ]
