# Generated by Django 2.2 on 2023-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_auto_20230207_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odoo_db_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
