# Generated by Django 2.2 on 2023-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_order_odoo_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odoo_status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Success', 'Success'), ('Failed', 'Failed'), ('Completed', 'Completed')], default='None', max_length=20, null=True),
        ),
    ]
