# Generated by Django 2.2 on 2023-04-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_auto_20230414_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
